#!/usr/bin/env node
const http=require('http');const fs=require('fs');const path=require('path');const {chromium}=require('playwright');
const root=path.resolve(__dirname,'..'),qa=path.join(root,'qa'),chrome=process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';fs.mkdirSync(qa,{recursive:true});
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.jpg':'image/jpeg','.md':'text/markdown; charset=utf-8'};
function serve(){return new Promise(resolve=>{const server=http.createServer((req,res)=>{const clean=decodeURIComponent(req.url.split('?')[0]);if(clean==='/favicon.ico'){res.writeHead(204);res.end();return}const file=path.resolve(root,'.'+(clean==='/'?'/index.html':clean));if(!file.startsWith(root+path.sep)||!fs.existsSync(file)||fs.statSync(file).isDirectory()){res.writeHead(404);res.end('Not found');return}res.writeHead(200,{'content-type':mime[path.extname(file)]||'application/octet-stream'});fs.createReadStream(file).pipe(res)});server.listen(0,'127.0.0.1',()=>resolve(server))})}
(async()=>{const failures=[],browserFailures=[];const server=await serve(),port=server.address().port;const browser=await chromium.launch({headless:true,executablePath:chrome});
const manifest=JSON.parse(fs.readFileSync(path.join(root,'charts','manifest.json'),'utf8'));const expected=[67,...manifest.families.map(f=>f.charts.length)];
const page=await browser.newPage({viewport:{width:1440,height:1000}});page.on('console',m=>{if(m.type()==='error')browserFailures.push(`console:${m.text()}`)});page.on('requestfailed',r=>browserFailures.push(`request:${r.url()}`));await page.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});await page.waitForFunction(()=>document.querySelectorAll('.chart-card').length===67);await page.waitForTimeout(500);
const desktop=await page.evaluate(()=>{const ref=document.querySelector('.painting img');return{cards:document.querySelectorAll('.chart-card').length,filters:document.querySelectorAll('#filters button').length,downloads:document.querySelectorAll('.chart-card a[download]').length,width:document.documentElement.scrollWidth,viewport:document.documentElement.clientWidth,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).length,reference:{width:ref.naturalWidth,height:ref.naturalHeight},eyebrow:document.querySelector('.eyebrow')?.textContent||''}});
const filterAudit=await page.evaluate(()=>{const out=[];const buttons=[...document.querySelectorAll('#filters button')];for(const button of buttons){button.click();out.push({label:button.textContent.trim(),cards:document.querySelectorAll('.chart-card').length})}buttons[0].click();return out});await page.screenshot({path:path.join(root,'assets','qianli-qinglu-preview.jpg'),type:'jpeg',quality:91});
const poster=await browser.newPage({viewport:{width:2400,height:1200}});poster.on('requestfailed',r=>browserFailures.push(`poster:${r.url()}`));await poster.goto(`http://127.0.0.1:${port}/src/qianli-qinglu-chart-vocabulary.html`,{waitUntil:'networkidle'});await poster.waitForFunction(()=>document.querySelectorAll('.family-panel').length===9&&document.querySelectorAll('.chart-shell svg').length===67);await poster.waitForTimeout(500);const posterMetrics=await poster.evaluate(()=>{const ref=document.querySelector('.art-reference img');return{width:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,families:document.querySelectorAll('.family-panel').length,charts:document.querySelectorAll('.chart-shell svg').length,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).length,reference:{width:ref.naturalWidth,height:ref.naturalHeight},edition:document.querySelector('.edition')?.textContent||''}});await poster.screenshot({path:path.join(root,'assets','qianli-qinglu-poster.png'),fullPage:true});await poster.evaluate(()=>document.documentElement.style.filter='grayscale(1)');await poster.screenshot({path:path.join(qa,'qianli-qinglu-poster-grayscale.png'),fullPage:true});
const mobile=await browser.newPage({viewport:{width:390,height:844}});mobile.on('requestfailed',r=>browserFailures.push(`mobile:${r.url()}`));await mobile.goto(`http://127.0.0.1:${port}/`,{waitUntil:'networkidle'});await mobile.waitForFunction(()=>document.querySelectorAll('.chart-card').length===67);await mobile.waitForTimeout(400);const mobileMetrics=await mobile.evaluate(()=>({width:document.documentElement.scrollWidth,viewport:document.documentElement.clientWidth,cards:document.querySelectorAll('.chart-card').length,broken:[...document.images].filter(i=>!i.complete||!i.naturalWidth).length,firstCardHeight:Math.round(document.querySelector('.chart-card').getBoundingClientRect().height)}));await mobile.screenshot({path:path.join(qa,'mobile-390.png'),fullPage:false});
if(manifest.version!=='2.0.0')failures.push('manifest version is not 2.0.0');if(desktop.cards!==67||desktop.filters!==10||desktop.downloads!==67||posterMetrics.families!==9||posterMetrics.charts!==67)failures.push('browser count mismatch');if(filterAudit.some((row,i)=>row.cards!==expected[i]))failures.push('filter count mismatch');if(desktop.width>desktop.viewport||mobileMetrics.width>mobileMetrics.viewport)failures.push('horizontal overflow');if(desktop.broken||posterMetrics.broken||mobileMetrics.broken)failures.push('broken image');if(desktop.reference.width!==2160||desktop.reference.height!==432||posterMetrics.reference.width!==2160||posterMetrics.reference.height!==432)failures.push('reference artwork dimensions changed');if(posterMetrics.width!==2400)failures.push(`poster width ${posterMetrics.width}`);if(!posterMetrics.edition.includes('2.0')||!desktop.eyebrow.includes('V2.0'))failures.push('visible version label missing');failures.push(...browserFailures);
await browser.close();server.close();const result={status:failures.length?'FAIL':'PASS',version:'2.0.0',desktop,filterAudit,poster:posterMetrics,mobile:mobileMetrics,failures};fs.writeFileSync(path.join(root,'validation.json'),JSON.stringify(result,null,2)+'\n');console.log(JSON.stringify(result,null,2));if(failures.length)process.exit(1)})().catch(error=>{console.error(error);process.exit(1)});
